<?php
// module/Carddb/view/carddb/carddb/missing.phtml:

$title = 'Oops! Something went wrong.';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('carddb', array('action' => 'results')));
$form->prepare();

echo $this->form()->openTag($form);

			$fields = array(
				'name',
				'text',
				'keywords',
				'rank',
				'suit',
				'control',
				'cost',
				'upkeep',
				'type',
				'outfit',
				'bullets',
				'bullet_bonus',
				'draw_type',
				'influence',
				'set_name',
			);
echo '<div class="row-fluid">';
echo '<div class="col-md-12 alert alert-danger">No Records were found. Please search again.</div>';
echo '</div>';
echo '<div class="row-fluid search-form-row">';
echo '<div class="col-md-3 alert alert-warning">Heads up! At the moment searching functionality is limited to exact terms. If you have any issues try searching again with different terms.</div>';
foreach ($fields as $key => $field) {
	if ($key % 5 == 0) {
		if ($key != 0) {
			echo '</div>';
		}
		echo '<div class="col-md-3">';
	}
	echo '<div class="span4 '.$field.'-field">'.$this->formRow($form->get($field)).'</div>';
}
echo '</div>';
echo '</div>';
echo '<div class="row-fluid">';
echo '<div class="col-md-3 col-md-offset-9">'.$this->formSubmit($form->get('submit')).'</div>';


echo $this->form()->closeTag();
echo '<div class="row-fluid"><div class="col-md-12"></div></div>';
