-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Aug 24, 2014 at 05:58 PM
-- Server version: 5.5.38-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `dtrdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `carddb`
--

DROP TABLE IF EXISTS `carddb`;
CREATE TABLE IF NOT EXISTS `carddb` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `set_name` varchar(255) NOT NULL DEFAULT 'Core Set',
  `card_number` int(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `rank` varchar(255) DEFAULT NULL,
  `suit` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `upkeep` int(11) DEFAULT NULL,
  `production` int(11) DEFAULT NULL,
  `bullets` varchar(25) DEFAULT NULL,
  `bullet_bonus` varchar(25) DEFAULT NULL,
  `draw_type` varchar(255) DEFAULT NULL,
  `influence` varchar(25) DEFAULT NULL,
  `control` int(11) DEFAULT NULL,
  `outfit` varchar(255) DEFAULT NULL,
  `keywords` text,
  `text` text,
  `flavor_text` text,
  `card_image` varchar(255) NOT NULL DEFAULT 'assets/cards/core/000.png',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=147 ;

--
-- Dumping data for table `carddb`
--

INSERT INTO `carddb` (`id`, `set_name`, `card_number`, `name`, `rank`, `suit`, `type`, `cost`, `upkeep`, `production`, `bullets`, `bullet_bonus`, `draw_type`, `influence`, `control`, `outfit`, `keywords`, `text`, `flavor_text`, `card_image`) VALUES
(1, 'Core Set', 59, '1st Baptist Church', '3', 'Diamonds', 'Deed', 3, NULL, NULL, '0', NULL, NULL, NULL, 2, NULL, 'Private-Holy Ground', 'Raise the controller’s hand size by one.', NULL, 'assets/cards/core/059.png'),
(2, 'Core Set', 135, 'A Coach Comes to Town', 'J', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon Job: Mark the town square. If successful, gain 4 ghost rock. If not, each player with a dude in the opposing posse gains 4 ghost rock.', NULL, 'assets/cards/core/135.png'),
(3, 'Core Set', 143, 'A Secret Tunnel', 'K', 'Clubs', 'Action', 1, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Move your dude from one in-town deed you own to another in-town deed you own (without booting). Make another Noon play.', NULL, 'assets/cards/core/143.png'),
(4, 'Core Set', 23, 'Abram Grothe ', 'J', 'Spades', 'Dude', 5, 1, NULL, '2', NULL, 'Stud', '1', NULL, 'Law Dogs', 'Deputy', 'Noon Job, Boot: Mark a Holy Ground deed. If successful, discard all Abominations and wanted dudes at that deed.', NULL, 'assets/cards/core/023.png'),
(5, 'Core Set', 101, 'Ace in the Hole', '3', 'Hearts', 'Spell', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Hex', 'React Hex 6, Boot: When you reveal your draw hand in a shootout, boot this Huckster. Ace a card in your draw hand. Replace it with a card from your play hand.', NULL, 'assets/cards/core/101.png'),
(6, 'Core Set', 35, 'Allie Hensman', 'A', 'Spades', 'Dude', 2, NULL, NULL, '2', NULL, 'Draw', NULL, NULL, 'The Sloane Gang', NULL, 'Noon, Boot: If Allie is at the town square, she permanently gets 1 control point.', NULL, 'assets/cards/core/035.png'),
(7, 'Core Set', 114, 'Ambush', '4', 'Clubs', 'Action', 4, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon Job, Boot: Mark a dude. If the mark is not wanted, raise the bounty on each dude in your posse by 1. If successful, ace the mark.', NULL, 'assets/cards/core/114.png'),
(8, 'Core Set', 20, 'Andreas Andregg', '5', 'Spades', 'Dude', 5, 1, NULL, '1', NULL, 'Stud', '2', NULL, 'Law Dogs', 'Deputy-Mad Scientist 0', NULL, NULL, 'assets/cards/core/020.png'),
(9, 'Core Set', 50, 'Androcles Brocklehurst', '7', 'Spades', 'Dude', 4, 1, NULL, '1', NULL, 'Draw', '2', NULL, 'Drifter', NULL, 'Noon, Boot: Choose another player’s dude at a deed you own but don’t control. Gain ghost rock equal to that dude’s influence.', NULL, 'assets/cards/core/050.png'),
(10, 'Core Set', 8, 'Arnold McCadish', '7', 'Spades', 'Dude', 5, NULL, NULL, '0', NULL, 'Draw', '2', NULL, 'The Fourth Ring', NULL, 'React, Pull, Boot: When a dude is discarded (not aced) as a casualty in a shootout, if the pull is higher than the dude’s value, send that dude home booted instead.', NULL, 'assets/cards/core/008.png'),
(11, 'Core Set', 111, 'Auction', '3', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Choose a deed in play. It becomes Private. If you own and control that deed, gain 1 ghost rock for each dude controlled by another player at that deed.', NULL, 'assets/cards/core/111.png'),
(12, 'Core Set', 99, 'Auto Cattle-Feeder', 'K', 'Hearts', 'Goods', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Gadget-Difficulty 7', 'After this is invented, attach it to a Ranch that you control.#xD;\r\nController Noon, Boot: Gain 1 ghost rock.', NULL, 'assets/cards/core/099.png'),
(13, 'Core Set', 89, 'Auto-Revolver', '7', 'Hearts', 'Goods', 1, NULL, NULL, '0', '1', 'Draw', NULL, NULL, NULL, 'Weapon-Gadget-Difficulty 7', 'You may equip this Gadget as a Shootout play (pay all costs).#xD;\r\nWhen forming a shootout hand, when you redraw after discarding at least one card, you may draw one extra card.', NULL, 'assets/cards/core/089.png'),
(14, 'Core Set', 10, 'Avie Cline', '10', 'Spades', 'Dude', 3, 2, NULL, '0', NULL, 'Draw', '2', NULL, 'The Fourth Ring', 'Harrowed-Huckster 0', NULL, NULL, 'assets/cards/core/010.png'),
(15, 'Core Set', 61, 'B&B Attorneys', '4', 'Diamonds', 'Deed', 2, NULL, 1, NULL, NULL, NULL, NULL, 1, NULL, 'Private', 'Controller Noon, Boot: Raise or lower the bounty on a wanted dude by one (if the bounty goes to zero, the dude is no longer wanted).', NULL, 'assets/cards/core/061.png'),
(16, 'Core Set', 117, 'Bad Company', '5', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, 'false', NULL, NULL, 'false', NULL, 'Noon: Choose a wanted dude. That dude gets +3 bullets and is a stud. If the dude is discarded or aced, the player responsible gains 4 extra ghost rock.', NULL, 'assets/cards/core/117.png'),
(17, 'Core Set', 55, 'Bank of California', 'A', 'Diamonds', 'Deed', 5, NULL, 3, NULL, NULL, NULL, NULL, 2, NULL, 'Public', 'Players cannot take ghost rock from the Bank’s controller.', NULL, 'assets/cards/core/055.png'),
(18, 'Core Set', 40, 'Barton Everest', '5', 'Spades', 'Dude', 4, 1, NULL, '2', NULL, 'Stud', '1', NULL, 'The Sloane Gang', NULL, 'If you reveal a cheatin’ hand in Barton’s shootout, raise your draw hand rank by 1 for this round..', NULL, 'assets/cards/core/040.png'),
(19, 'Core Set', 67, 'Blake Ranch', '7', 'Diamonds', 'Deed', 4, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'Private-Ranch-Out of Town', 'Private • Ranch#xD;\nOut of Town', NULL, 'assets/cards/core/067.png'),
(20, 'Core Set', 103, 'Blood Curse', 'Q', 'Hearts', 'Spell', 1, NULL, NULL, '0', NULL, 'false', NULL, NULL, 'false', 'Hex', 'Noon Hex 9, Boot: A dude at this or an adjacent location gets –1 influence and –1 bullets.\r\nShootout Hex 9, Boot: One opposing dude gets –2 bullets.', NULL, 'assets/cards/core/103.png'),
(21, 'Core Set', 82, 'Bluetick', '2', 'Hearts', 'Goods', 2, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Sidekick', 'Sidekick (This card can be discarded to cover one casualty.)\r\nNoon, Boot: Move this dude to the same location as a wanted dude.', NULL, 'assets/cards/core/082.png'),
(22, 'Core Set', 7, 'Bobo', '6', 'Spades', 'Dude', 1, 3, NULL, '1', NULL, 'Stud', '1', NULL, 'The Fourth Ring', 'Abomination', 'Bobo gains a bullet bonus equal to the highest Huckster skill rating in play.', NULL, 'assets/cards/core/007.png'),
(23, 'Core Set', 108, 'Bottom Dealin''', '2', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Cheatin’ Resolution:Discard the cheatin’ player’s draw hand and replace it with the top five cards of your deck (those cards still go to your discard pile).', NULL, 'assets/cards/core/108.png'),
(24, 'Core Set', 126, 'Bounty Hunter', '8', 'Clubs', 'Action', 2, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: A 2-stud Gunslinger token enters play at a wanted dude’s location. The Gunslinger calls out that dude, who cannot refuse. Remove the Gunslinger token from the game after the shootout.', NULL, 'assets/cards/core/126.png'),
(25, 'Core Set', 97, 'Buffalo Rifle', 'J', 'Hearts', 'Goods', 2, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Weapon', 'If this dude is adjacent to the location of a shootout or a job’s mark, they can join a posse, without moving or booting, even if booted.', NULL, 'assets/cards/core/097.png'),
(26, 'Core Set', 71, 'Bunkhouse', '9', 'Diamonds', 'Deed', 2, NULL, 1, NULL, NULL, NULL, NULL, 1, NULL, 'Private', 'Dudes with 0 or 1 influence have +1 influence while at this deed.', NULL, 'assets/cards/core/071.png'),
(27, 'Core Set', 73, 'Carter''s Bounties', '10', 'Diamonds', 'Deed', 2, NULL, 1, NULL, NULL, NULL, NULL, 1, NULL, 'Private', 'Controller Shootout, Boot: Move your dude into your posse from any location.', NULL, 'assets/cards/core/073.png'),
(28, '', 68, 'Cattle Market', '7', 'Diamonds', 'Deed', 4, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Private-Ranch', 'This deed has 1 control point if another Ranch is in play.\r\nAll dudes have their value raised by 3 while at this deed.', NULL, 'assets/cards/core/068.png'),
(29, 'Core Set', 63, 'Charlie''s Place', '5', 'Diamonds', 'Deed', 3, NULL, 2, NULL, NULL, NULL, NULL, 1, NULL, 'Public-Saloon', 'Controller Noon, Boot: Raise or lower the bullets of a dude at this location by 2.', NULL, 'assets/cards/core/063.png'),
(30, 'Core Set', 129, 'Cheatin'' Varmint', '9', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Resolution: Pay 5 ghost rock to lower a player’s draw hand by 2 ranks.\r\nCheatin’ Resolution: Lower a player’s draw hand by 2 ranks.', NULL, 'assets/cards/core/129.png'),
(31, 'Core Set', 69, 'Circle M Ranch', '8', 'Diamonds', 'Deed', 3, NULL, 2, NULL, NULL, NULL, NULL, 1, NULL, 'Private-Ranch', 'Controller Noon, Boot: If you have 3 or fewer cards in your play hand, draw a card.', NULL, 'assets/cards/core/069.png'),
(32, 'Core Set', 138, 'Clear Out!', 'Q', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Move your dude to a deed that you own but do not control.', NULL, 'assets/cards/core/138.png'),
(33, 'Core Set', 45, 'Clementine Lepp', 'A', 'Spades', 'Dude', 3, NULL, NULL, '0', NULL, 'Draw', '1', NULL, 'Drifter', NULL, 'While in a Saloon you own, Clementine gets +1 influence and cannot be called out.', NULL, 'assets/cards/core/045.png'),
(34, 'Core Set', 53, 'Clint Ramsey', 'J', 'Spades', 'Dude', 5, 1, NULL, '2', NULL, 'Stud', '1', NULL, 'Drifter', NULL, NULL, NULL, 'assets/cards/core/053.png'),
(35, 'Core Set', 22, 'Clyde Owens', '10', 'Spades', 'Dude', 7, 2, NULL, '3', NULL, 'Stud', '2', NULL, 'Law Dogs', NULL, 'Noon: Clyde calls out a dude at his location. A wanted dude cannot refuse the call out.', NULL, 'assets/cards/core/022.png'),
(36, 'Core Set', 115, 'Coachwhip!', '4', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Cheatin’ Resolution: The cheatin’ player must boot a dude. If in a shootout, that dude gets aced instead. If you have a legal hand, you choose the dude to boot or ace.', NULL, 'assets/cards/core/115.png'),
(37, 'Core Set', 120, 'Concealed Weapons', '6', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: You may use shoppin’ as a Shootout play, and at any location.', NULL, 'assets/cards/core/120.png'),
(38, 'Core Set', 62, 'Dead Dog Tavern', '4', 'Diamonds', 'Deed', 4, NULL, 2, NULL, NULL, NULL, NULL, 1, NULL, 'Private-Saloon', 'Determine control of this deed using bullets instead of influence.', NULL, 'assets/cards/core/062.png'),
(39, 'Core Set', 96, 'Doyle''s Hoyle', '10', 'Hearts', 'Goods', 3, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Mystical', 'React, Boot: If this dude makes a pull or is in a posse, you may discard the pull or a card from your draw hand to replace it with this card. If the discarded card was a 2, raise your draw hand rank by one.', NULL, 'assets/cards/core/096.png'),
(40, 'Core Set', 52, 'Dr. Dawn Edwards', '9', 'Spades', 'Dude', 5, 1, NULL, '0', NULL, 'Draw', '2', NULL, 'Drifter', 'Mad Scientist 0', 'If you discard Dawn as a casualty, you may search your deck for Eve Henry (if you don’t already have her in play), and play her for free at this location. Shuffle your deck.', NULL, 'assets/cards/core/052.png'),
(41, 'Core Set', 27, 'Elander Boldman', '6', 'Spades', 'Dude', 6, NULL, NULL, '0', NULL, 'Draw', '1', NULL, 'Morgan Cattle Co.', 'Mad Scientist 2', 'Shootout, Pull: Choose your dude with a Weapon Gadget in this shootout. If the pull is a club, discard that dude. Otherwise, that Gadget gets +3 bullets.', NULL, 'assets/cards/core/027.png'),
(42, 'Core Set', 105, 'Establishin'' Who''s in Charge', 'A', 'Clubs', 'Action', 1, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon Job: Mark an in-town deed. If successful, the deed permanently gains 1 control point.', NULL, 'assets/cards/core/105.png'),
(43, 'Core Set', 54, 'Eve Henry', 'Q', 'Spades', 'Dude', 5, 2, NULL, '3', NULL, 'Stud', '1', NULL, 'Drifter', 'Abomination', 'If you discard Eve as a casualty, you may search your deck for Dr. Dawn Edwards (if you don’t already have her in play), and play her for free at this location. Shuffle your deck.', NULL, 'assets/cards/core/054.png'),
(44, 'Core Set', 132, 'Extortion', '10', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Choose a deed that you control but do not own. Gain ghost rock equal to its production.', NULL, 'assets/cards/core/132.png'),
(45, 'Core Set', 91, 'Flame-Thrower', '8', 'Hearts', 'Goods', 2, NULL, NULL, '0', '1', 'Stud', NULL, NULL, NULL, 'Weapon-Gadget-Difficulty 8', 'This dude is a stud.\r\nShootout, Pay 1–3 Ghost Rock, Boot: Raise the bullets on this Gadget by 1 for each ghost rock spent. Each round’s loser takes 1 extra casualty.', NULL, 'assets/cards/core/091.png'),
(46, 'Core Set', 92, 'Force Field', '8', 'Hearts', 'Goods', 1, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Gadget-Difficulty 5', 'Repeat Resolution, Pay X Ghost Rock: Raise your draw hand rank by X for this round, but not to exceed your opponent’s hand rank.', NULL, 'assets/cards/core/092.png'),
(47, 'Core Set', 36, 'Fred Aims', '2', 'Spades', 'Dude', 4, NULL, NULL, '2', NULL, 'Draw', '0', NULL, 'The Sloane Gang', NULL, 'Fred’s influence is equal to his bounty.', NULL, 'assets/cards/core/036.png'),
(48, 'Core Set', 130, 'Fresh Horses', '9', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Unboot all your Horses at one location. Any abilities on the Horses that have been used can be used an extra time.', NULL, 'assets/cards/core/130.png'),
(49, 'Core Set', 77, 'General Store', 'Q', 'Diamonds', 'Deed', 2, NULL, 1, NULL, NULL, NULL, NULL, 1, NULL, 'Private', 'Controller Noon, Boot: Attach a goods or spell (as shoppin’), reducing the cost of that card by 2 ghost rock.', NULL, 'assets/cards/core/077.png'),
(50, 'Core Set', 57, 'Gomorra Parish', '2', 'Diamonds', 'Deed', 3, NULL, 1, NULL, NULL, NULL, NULL, 1, NULL, 'Private-Holy Ground', 'Controller Noon, Boot: Ace a card from your hand to gain 1 ghost rock.', NULL, 'assets/cards/core/057.png'),
(51, 'Core Set', 141, 'Good Stiff Drink', 'K', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Choose a dude’s ability that has been used. That ability can be used another time.', '"Got anything stronger?" --Prescott Utter', 'assets/cards/core/141.png'),
(52, 'Core Set', 32, 'Harold Aimslee', '10', 'Spades', 'Dude', 9, 2, NULL, '1', NULL, 'Stud', '3', NULL, 'Morgan Cattle Co.', 'Mad Scientist 2', 'Noon, Boot: Discard a card from your hand to get a non-Weapon Gadget from your discard pile. Show the card and add it to your hand.', NULL, 'assets/cards/core/032.png'),
(53, 'Core Set', 136, 'Hex Slingin''', 'J', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Resolution: Discard a Hex from your dude in this posse to raise your draw hand rank by 2.', NULL, 'assets/cards/core/136.png'),
(54, 'Core Set', 118, 'Hiding in the Shadows', '5', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Choose one of your dudes. Other players cannot choose or affect that dude with Shootout abilities.', NULL, 'assets/cards/core/118.png'),
(55, 'Core Set', 106, 'Hired Guns', 'A', 'Clubs', 'Action', 1, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Place a dude from your discard pile into your hand.', 'Their aim don''t matter if there''s enough of them.', 'assets/cards/core/106.png'),
(56, 'Core Set', 121, 'Hot Lead Flyin''', '6', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'React: After you take casualties forlosing a round of a shootout, pull. For each dude you have (still in the posse) with a value higher than the pull, the winner takes 1 casualty.', NULL, 'assets/cards/core/121.png'),
(57, 'Core Set', 25, 'Irving Patterson', 'A', 'Spades', 'Dude', 3, NULL, NULL, '0', NULL, 'Draw', '2', NULL, 'Morgan Cattle Co.', NULL, 'When Irving joins a posse, gain 1 ghost rock.', NULL, 'assets/cards/core/025.png'),
(58, 'Core Set', 14, 'Ivor Hawley', 'K', 'Spades', 'Dude', 9, 2, NULL, '1', NULL, 'Stud', '3', NULL, 'The Fourth Ring', 'Abomination-Huckster 2', 'While he has a Hex, Ivor gets +1 bullets, +1 influence, and +1 Huckster skill.', NULL, 'assets/cards/core/014.png'),
(59, 'Core Set', 75, 'Jackson''s Strike', 'J', 'Diamonds', 'Deed', 2, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'Private-Strike-Out of Town', NULL, NULL, 'assets/cards/core/075.png'),
(60, 'Core Set', 28, 'James Ghetty', '7', 'Spades', 'Dude', 7, 1, NULL, '1', NULL, 'Stud', '2', NULL, 'Morgan Cattle Co.', 'Mad Scientist 0', 'When James enters a posse, place 4 ghost rock on him. The ghost rock may be used to pay for Shootout abilities (it is not a bounty). Discard his unused ghost rock after the shootout.', NULL, 'assets/cards/core/028.png'),
(61, 'Core Set', 31, 'Jarrett Blake', '9', 'Spades', 'Dude', 5, 1, NULL, '2', NULL, 'Stud', '1', NULL, 'Morgan Cattle Co.', NULL, 'Shootout: If Jarrett has a Horse, swap him with one of your dudes in the posse (Jarrett joins the posse. The other dude moves to Jarrett’s location and is no longer in the posse).', NULL, 'assets/cards/core/031.png'),
(62, 'Core Set', 13, 'Jia Mein', 'Q', 'Spades', 'Dude', 7, 1, NULL, '2', NULL, 'Draw', '2', NULL, 'The Fourth Ring', 'Huckster 1', 'Shootout: Attach a Hex to Jia Mein (paying all costs) to make him a stud.', NULL, 'assets/cards/core/013.png'),
(63, 'Core Set', 144, 'Joker (red)', '*', NULL, 'Joker', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'This card is only used for draw hands and pulls.\r\nYou choose its suit and value. Ace the joker after use.', NULL, 'assets/cards/core/144.png'),
(64, 'Core Set', 145, 'Joker (black)', '*', NULL, 'Joker', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'This card is only used for draw hands and pulls.\r\nYou choose its suit and value. Ace the joker after use.', NULL, 'assets/cards/core/145.png'),
(65, 'Core Set', 29, 'Jon Longstride', '8', 'Spades', 'Dude', 4, NULL, NULL, '2', NULL, 'Draw', '1', NULL, 'Morgan Cattle Co.', NULL, 'Noon: Unboot Jon’s Horse. You may use the Horse’s ability an additional time.', NULL, 'assets/cards/core/029.png'),
(66, 'Core Set', 42, 'Jonah Essex', '6', 'Spades', 'Dude', 6, 2, NULL, '2', NULL, 'Stud', '2', NULL, 'The Sloane Gang', 'Huckster 1', 'Other wanted dudes in Jonah’s posse get +1 bullets.', NULL, 'assets/cards/core/042.png'),
(67, 'Core Set', 16, 'Judge Harry Somerset', '2', 'Spades', 'Dude', 6, 2, NULL, '1', NULL, 'Draw', '3', NULL, 'Law Dogs', 'Deputy', 'Noon Job, Boot: Harry leads a job that marks a wanted dude. If successful, ace the mark.', NULL, 'assets/cards/core/016.png'),
(68, 'Core Set', 11, 'Kevin Wainwright', 'J', 'Spades', 'Dude', 5, 1, NULL, '3', NULL, 'Draw', '1', NULL, 'The Fourth Ring', NULL, 'Noon: Move Kevin (without booting) to the same location as a Huckster. Kevin becomes a stud.', NULL, 'assets/cards/core/011.png'),
(69, 'Core Set', 123, 'Kidnappin''', '7', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon Job, Boot: Mark a dude. Your posse must have more total bullets than the marked dude. Raise the bounty of each dude in your posse by 1. If successful, discard the mark.', '"Welcome to the circus!" --Bobo', 'assets/cards/core/123.png'),
(70, 'Core Set', 65, 'Killer Bunnies Casino', '6', 'Diamonds', 'Deed', 4, NULL, 2, NULL, NULL, NULL, NULL, 1, NULL, 'Public-Saloon-Casino', 'The controller of this deed may discard one additional card each Sundown phase.', NULL, 'assets/cards/core/065.png'),
(71, 'Core Set', 107, 'Lady Luck', 'A', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: You can discard as many of your cards as you like during Sundown.', NULL, 'assets/cards/core/107.png'),
(72, 'Core Set', 30, 'Lane Healey', '8', 'Spades', 'Dude', 6, 2, NULL, '1', NULL, 'Stud', '3', NULL, 'Morgan Cattle Co.', NULL, 'Lane gets +2 bullets while he has a Horse.', NULL, 'assets/cards/core/030.png'),
(73, 'Core Set', 2, 'Law Dogs', NULL, NULL, 'Outfit', 19, NULL, 3, NULL, NULL, NULL, NULL, NULL, 'Law Dogs', NULL, 'Noon, Boot: Choose a dude. Boot your dudes with a total influence greater than the chosen dude’s influence to raise that dude’s bounty by 1.', NULL, 'assets/cards/core/002.png'),
(74, 'Core Set', 37, 'Lawrence Blackwood', '3', 'Spades', 'Dude', 3, NULL, NULL, '1', NULL, 'Draw', '1', NULL, 'The Sloane Gang', NULL, 'Noon, Boot: If Lawrence is at a deed you do not own, he is worth 1 control point while he stays at that deed.', NULL, 'assets/cards/core/037.png'),
(75, 'Core Set', 98, 'Legendary Holster', 'Q', 'Hearts', 'Goods', 4, NULL, NULL, '0', '2', 'Draw', NULL, NULL, NULL, 'Weapon-Mystical-Unique', 'Shootout Pull, Boot: If the pull is lower than this dude’s bullets, ace one dude in the opposing posse.', NULL, 'assets/cards/core/098.png'),
(76, 'Core Set', 15, 'Lucinda "Lucy" Clover', 'A', 'Spades', 'Dude', 2, 1, NULL, '0', NULL, 'Draw', '2', NULL, 'Law Dogs', NULL, 'If your opponent in Lucy’s shootout reveals a cheatin’ hand, raise the bounty on each dude in their posse by 1 (including from 0 to 1).', NULL, 'assets/cards/core/015.png'),
(77, 'Core Set', 131, 'Magical Distraction', '9', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Cheatin’ Resolution: Discard a spell from your dude in this posse and pull. Your draw hand rank equals the value of your pull (to a 0 maximum rank of 11).', NULL, 'assets/cards/core/131.png'),
(78, 'Core Set', 109, 'Make the Smart Choice', '2', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Shootout: Reduce a dude’s bullets by their influence. The dude’s controller may move them home booted (even if already booted).', NULL, 'assets/cards/core/109.png'),
(79, 'Core Set', 38, 'Marion Seville', '4', 'Spades', 'Dude', 3, 1, NULL, '1', NULL, 'Draw', '2', NULL, 'The Sloane Gang', NULL, 'Marion gets +2 bullets while he is wanted.', NULL, 'assets/cards/core/038.png'),
(80, 'Core Set', 34, 'Max Baine', 'Q', 'Spades', 'Dude', 6, 3, NULL, '2', NULL, 'Draw', '4', NULL, 'Morgan Cattle Co.', NULL, 'Max is worth 1 control point while you control 2 or more Ranches.\r\nYour other dudes at Ranches get +1 influence and +3 value.', NULL, 'assets/cards/core/034.png'),
(81, 'Core Set', 94, 'Mechanical Horse', '9', 'Hearts', 'Goods', 1, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Horse-Gadget-Difficulty 5', 'Repeat Noon, Pay 2 Ghost Rock: Move this dude.\r\nReact, Boot: Prevent this dude from booting when they join a posse (this does not let a booted dude join a posse).', NULL, 'assets/cards/core/094.png'),
(82, 'Core Set', 5, 'Micah Ryse', '2', 'Spades', 'Dude', 5, NULL, NULL, '0', NULL, 'Stud', '1', NULL, 'The Fourth Ring', 'Huckster 0', 'Noon: Boot a Hex on Micah to move him (without booting).', NULL, 'assets/cards/core/005.png'),
(83, 'Core Set', 139, 'Missed!', 'Q', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Shootout: Unboot one of your dudes in this posse.', NULL, 'assets/cards/core/139.png'),
(84, 'Core Set', 6, 'Mongwau the Mighty', '3', 'Spades', 'Dude', 5, 1, NULL, '3', NULL, 'Draw', '1', NULL, 'The Fourth Ring', 'Huckster 1', 'Shootout: Discard a Hex from Mongwau to make him a stud.', NULL, 'assets/cards/core/006.png'),
(85, 'Core Set', 3, 'Morgan Cattle Co.', NULL, NULL, 'Outfit', 18, NULL, 3, NULL, NULL, NULL, NULL, NULL, 'Morgan Cattle Co.', NULL, 'Noon, Boot: Boot one of your dudes to play a deed, reducing the deed’s cost by the dude’s influence. Move that dude to that deed.', NULL, 'assets/cards/core/003.png'),
(86, 'Core Set', 86, 'Mustang', '5', 'Hearts', 'Goods', 3, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Horse', 'Noon, Boot: Move this dude (without booting).', NULL, 'assets/cards/core/086.png'),
(87, 'Core Set', 46, 'Olivia Jenks', '2', 'Spades', 'Dude', 3, 1, NULL, '2', NULL, 'Draw', '2', NULL, 'Drifter', NULL, NULL, NULL, 'assets/cards/core/046.png'),
(88, 'Core Set', 122, 'One Good Turn…', '6', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Draw a card.\r\nCheatin'' Resolution: Gain 3 ghost rock.', NULL, 'assets/cards/core/122.png'),
(89, 'Core Set', 81, 'Pair of Six-Shooters', 'A', 'Hearts', 'Goods', 1, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Weapon', 'Cheatin’ Resolution, Boot: One card in your draw hand changes to the suit and value of your choice.', NULL, 'assets/cards/core/081.png'),
(90, 'Core Set', 41, 'Pancho Castillo', '5', 'Spades', 'Dude', 5, 2, NULL, '3', NULL, 'Stud', '2', NULL, 'The Sloane Gang', NULL, NULL, NULL, 'assets/cards/core/041.png'),
(91, 'Core Set', 70, 'Pat''s Perch', '8', 'Diamonds', 'Deed', 1, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Private-Strike-Out of Town', NULL, NULL, 'assets/cards/core/070.png'),
(92, 'Core Set', 83, 'Peacemaker', '2', 'Hearts', 'Goods', 2, NULL, NULL, '0', '1', 'Draw', NULL, NULL, NULL, 'Weapon', 'This dude cannot be changed to a draw, and cannot have their bullets lowered by another player’s Shootout ability.', NULL, 'assets/cards/core/083.png'),
(93, 'Core Set', 87, 'Pearl-handled Revolver', '5', 'Hearts', 'Goods', 1, NULL, NULL, '0', NULL, 'Stud', NULL, NULL, NULL, 'Weapon', 'This dude is a stud.', NULL, 'assets/cards/core/087.png'),
(94, 'Core Set', 64, 'Pearly''s Palace', '5', 'Diamonds', 'Deed', 5, NULL, 3, NULL, NULL, NULL, NULL, 1, NULL, 'Public-Saloon', 'Controller React, Boot: After a shootout starts but before any player makes a Shootout play, make a Shootout play.', NULL, 'assets/cards/core/064.png'),
(95, 'Core Set', 17, 'Philip Swinford', '2', 'Spades', 'Dude', 3, NULL, NULL, '1', NULL, 'Draw', '1', NULL, 'Law Dogs', 'Deputy', 'Each time a player reveals a cheatin’ hand and your hand is legal, you may discard a card from your play hand to draw a card.', NULL, 'assets/cards/core/017.png'),
(96, 'Core Set', 124, 'Pinned Down', '7', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Shootout: Choose a dude. They must be selected as the first casualty. If that dude is chosen as the shooter, they get –3 bullets (minimum 0).', NULL, 'assets/cards/core/124.png'),
(97, 'Core Set', 90, 'Pinto', '7', 'Hearts', 'Goods', 2, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Horse', 'Shootout, Boot: Move this dude into a posse (without booting; this can move a booted dude).', NULL, 'assets/cards/core/090.png'),
(98, 'Core Set', 119, 'Pistol Whip', '5', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Shootout: Boot your dude in this posse to send a dude in the other posse home booted. Your dude gets –1 bullets (minimum 0).', NULL, 'assets/cards/core/119.png'),
(99, 'Core Set', 142, 'Point Blank', 'K', 'Clubs', 'Action', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, 'Resolution: Boot your stud dude in this posse. Your opponent must ace a dude in their posse with lower bullets than your dude’s bullets.', 'At that kind of range you''re sure to hit something.', 'assets/cards/core/142.png'),
(100, 'Core Set', 56, 'Pony Express', 'A', 'Diamonds', 'Deed', 4, NULL, 2, NULL, NULL, NULL, NULL, 1, NULL, 'Public', 'Controller Noon, Boot: Discard a card to draw a card.', NULL, 'assets/cards/core/056.png'),
(101, 'Core Set', 19, 'Prescott Utter', '4', 'Spades', 'Dude', 5, 1, NULL, '?', NULL, 'Draw', '?', NULL, 'Law Dogs', NULL, 'Prescott’s bullets and influence are equal to the number of Law Dogs at his location (including himself).', NULL, 'assets/cards/core/019.png'),
(102, 'Core Set', 26, 'Prof. Eustace True', '4', 'Spades', 'Dude', 5, 1, NULL, '1', NULL, 'Draw', '2', NULL, 'Morgan Cattle Co.', 'Mad Scientist 1', 'Noon: Discard a Gadget from Eustace to move him to another location (without booting).', NULL, 'assets/cards/core/026.png'),
(103, 'Core Set', 93, 'Quickdraw Handgun', '8', 'Hearts', 'Goods', 2, NULL, NULL, NULL, '1', 'Draw', NULL, NULL, NULL, 'Weapon', 'Cheatin’ Resolution, Boot: If you have a legal draw hand, exchange draw hands with the cheatin’ player.\r\nCheatin’ cards cannot be played on you for this round of the shootout.', NULL, 'assets/cards/core/093.png'),
(104, 'Core Set', 79, 'Railroad Station', 'K', 'Diamonds', 'Deed', 2, NULL, 1, NULL, NULL, NULL, NULL, 1, NULL, 'Private', 'Controller Noon, Boot: Move your dude from this location to another location (without booting).', NULL, 'assets/cards/core/079.png'),
(105, 'Core Set', 104, 'Raising Hell', 'K', 'Hearts', 'Spell', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hex', 'Shootout Hex 8, Boot: Ace a card from your play hand. One Abomination from your Boot Hill enters play (pay all costs) and joins this Huckster’s posse. Ace this card.', NULL, 'assets/cards/core/104.png'),
(106, 'Core Set', 47, 'Ramiro Mendoza', '3', 'Spades', 'Dude', 3, 1, NULL, '3', NULL, 'Stud', '1', NULL, 'Drifter', NULL, 'Whenever Ramiro joins a posse, pay 1 ghost rock.#xD;\r\nIf you do not or cannot pay, discard him.', NULL, 'assets/cards/core/047.png'),
(107, 'Core Set', 133, 'Recruitment Drive', '10', 'Clubs', 'Action', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Noon Job: Mark the town square (any player may oppose the job). If successful, put a dude or deed into play from your discard pile, reducing its cost by 5 ghost rock.', NULL, 'assets/cards/core/133.png'),
(108, 'Core Set', 33, 'Rémy Lapointe', 'J', 'Spades', 'Dude', 7, 1, NULL, '1', NULL, 'Stud', '2', NULL, 'Morgan Cattle Co.', NULL, 'Shootout, Pay 1–4 Ghost Rock: Rémy gets +1 bullets for each ghost rock spent, to a maximum rating of 5 bullets.', NULL, 'assets/cards/core/033.png'),
(109, 'Core Set', 127, 'Reserves', '8', 'Clubs', 'Action', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Gain 1 ghost rock.', NULL, 'assets/cards/core/127.png'),
(110, 'Core Set', 88, 'Roan', '6', 'Hearts', 'Goods', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Horse', 'React, Boot: Prevent this dude from booting when they join a posse (this does not allow a booted dude to join a posse).', NULL, 'assets/cards/core/088.png'),
(111, 'Core Set', 128, 'Rumors', '8', 'Clubs', 'Action', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Choose a dude. That dude gets –1 influence while at any location except home.', NULL, 'assets/cards/core/128.png'),
(112, 'Core Set', 125, 'Run ''em Down!', '7', 'Clubs', 'Action', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Choose any number of your dudes, each with a Horse, at one location. Move them to an adjacent location that has an opposing dude without a Horse. Boot that dude. You may call that dude out.', NULL, 'assets/cards/core/125.png'),
(113, 'Core Set', 39, 'Sanford Taylor', '4', 'Spades', 'Dude', 5, 1, NULL, '2', NULL, 'Stud', '1', NULL, 'The Sloane Gang', NULL, 'Noon, Boot: Call out a dude at this deed. If Sanford is wanted, the call-out cannot be refused.', NULL, 'assets/cards/core/039.png'),
(114, 'Core Set', 102, 'Shadow Walk', '10', 'Hearts', 'Spell', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hex', 'Noon Hex 7, Boot: Move this Huckster to any location.\r\nShootout Hex 7, Boot: Move this Huckster to join your posse. You may make another Shootout play.', NULL, 'assets/cards/core/102.png'),
(115, 'Core Set', 24, 'Sheriff Dave Montreal', 'K', 'Spades', 'Dude', 9, 2, NULL, '3', NULL, 'Stud', '3', NULL, 'Law Dogs', 'Deputy', 'If your opponent in Dave’s shootout reveals a cheatin’ hand and you do not, your dudes cannot be casualties this round.', NULL, 'assets/cards/core/024.png'),
(116, 'Core Set', 84, 'Shotgun', '3', 'Hearts', 'Goods', 3, NULL, NULL, NULL, '1', 'Draw', NULL, NULL, NULL, 'Weapon', 'Shootout, Boot: Choose and ace an opposing dude in this shootout with a value less than or equal to this dude’s bullets.', NULL, 'assets/cards/core/084.png'),
(117, 'Core Set', 43, 'Silas Aims', NULL, 'Spades', 'Dude', 2, NULL, NULL, '?', NULL, 'Draw', NULL, NULL, 'The Sloane Gang', NULL, 'Silas’s bullets are equal to his bounty.', NULL, 'assets/cards/core/043.png'),
(118, 'Core Set', 44, 'Sloane', '', 'Spades', 'Dude', 8, 3, NULL, '4', NULL, 'Stud', '3', NULL, 'The Sloane Gang', NULL, 'Sloane’s bounty cannot be reduced below 1.#xD;\nSloane and your other dudes at her location do not boot when forming or joining a posse.', NULL, 'assets/cards/core/044.png'),
(119, 'Core Set', 100, 'Soul Blast', 'A', 'Hearts', 'Spell', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hex', 'Shootout Hex X, Boot: Choose a dude in this shootout. X is that dude’s grit. If successful, send the dude home booted. If successful by 6 or more, ace the dude instead. If unsuccessful, move this Huckster home booted.', NULL, 'assets/cards/core/100.png'),
(120, 'Core Set', 66, 'Stagecoach Office', '6', 'Diamonds', 'Deed', 1, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'Public', 'Controller React, Boot: When you bring a non-token dude into play, place that dude at any location you control.', NULL, 'assets/cards/core/066.png'),
(121, 'Core Set', 48, 'Steele Archer', '4', 'Spades', 'Dude', 5, 1, NULL, '0', NULL, 'Draw', '2', NULL, 'Drifter', 'Huckster 2', NULL, NULL, 'assets/cards/core/048.png'),
(122, 'Core Set', 51, 'Steven Wiles', '8', 'Spades', 'Dude', 1, 6, NULL, '3', NULL, 'Stud', '3', NULL, 'Drifter', NULL, NULL, NULL, 'assets/cards/core/051.png'),
(123, 'Core Set', 113, 'Sun in Yer Eyes', '3', 'Clubs', 'Action', NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Shootout: Choose a dude in this shootout. That dude gets –2 bullets (minimum 0) and becomes a draw.', NULL, 'assets/cards/core/113.png'),
(124, 'Core Set', 140, 'Takin'' Ya With Me', 'Q', 'Clubs', 'Action', NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'React: After you take casualties for losing a round of a shootout, your opponent takes 1 casualty unless each dude in their posse has higher bullets than the highest bullets among your casualties.', NULL, 'assets/cards/core/140.png'),
(125, 'Core Set', 80, 'Telegraph Office', 'K', 'Diamonds', 'Deed', 4, NULL, 1, NULL, NULL, NULL, NULL, 2, NULL, 'Private', 'Controller Noon, Boot: Choose a dude that was brought into play this Noon phase. Gain ghost rock equal to the dude’s influence.', NULL, 'assets/cards/core/080.png'),
(126, 'Core Set', 1, 'The Fourth Ring', NULL, NULL, 'Outfit', 19, NULL, 3, NULL, NULL, NULL, NULL, NULL, 'The Fourth Ring', NULL, 'React, Boot: After your dude succeeds at a spell pull while not at home, you may discard a card from your hand to gain 1 ghost rock and draw a card.', NULL, 'assets/cards/core/001.png'),
(127, 'Core Set', 9, 'The Ghostly Gun', '8', 'Spades', 'Dude', 7, 1, NULL, '2', NULL, 'Stud', '2', NULL, 'The Fourth Ring', 'Abomination', 'Resolution: Put The Ghostly Gun into your draw hand; he becomes the suit and value of your choice. Discard a card from your draw hand.', NULL, 'assets/cards/core/009.png'),
(128, 'Core Set', 72, 'Morgan Research Institute', '9', 'Diamonds', 'Deed', 5, NULL, 3, NULL, NULL, NULL, NULL, 1, NULL, 'Private', 'Controller Noon, Boot: Raise or lower the skill rating of a dude at this location by 2 (the skills are Huckster, Blessed, Shaman, and Mad Scientist).', NULL, 'assets/cards/core/072.png'),
(129, 'Core Set', 78, 'The Pharmacy', 'Q', 'Diamonds', 'Deed', 4, NULL, 1, '', NULL, NULL, NULL, 2, NULL, 'Private', 'Controller Noon, Boot: Unboot a dude.', NULL, 'assets/cards/core/078.png'),
(130, 'Core Set', 4, 'The Sloane Gang', NULL, NULL, 'Outfit', 18, NULL, 3, NULL, NULL, NULL, NULL, NULL, 'The Sloane Gang', NULL, 'Noon, Boot: Boot your dude in the town square. If that dude is still in the town square during the Sundown phase, either gain 1 ghost rock per other player, or your dude permanently gets 1 control point if they do not already have one.', NULL, 'assets/cards/core/004.png'),
(131, 'Core Set', 112, 'The Stakes Just Rose', '3', 'Clubs', 'Action', NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Shootout: Move one of your dudes into your posse. That dude becomes a stud.', NULL, 'assets/cards/core/112.png'),
(132, 'Core Set', 58, 'The Town Hall', '2', 'Diamonds', 'Deed', 5, NULL, 2, '', NULL, NULL, NULL, 2, NULL, 'Government-Public', 'Government • Controller React, Boot: At the start of the Upkeep phase, choose a dude at this location. Lower that dude’s upkeep by their influence.', NULL, 'assets/cards/core/058.png'),
(133, 'Core Set', 74, 'The Union Casino', '10', 'Diamonds', 'Deed', 5, NULL, 3, '', NULL, NULL, NULL, 1, NULL, 'Public-Casino-Saloon', 'Controller Noon, Boot: Choose your dude at this location and pay any amount of ghost rock. Each other player may then pay any amount of ghost rock. If you paid at least 4 ghost rock more than any other player, your dude permanently gets 1 control point.', NULL, 'assets/cards/core/074.png'),
(134, 'Core Set', 137, 'This is a Holdup!', 'J', 'Clubs', 'Action', NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Boot your dude at a deed you don’t own to take ghost rock from the owner up to the production of that deed. Raise the bounty on your dude by the amount of ghost rock taken.', NULL, 'assets/cards/core/137.png'),
(135, 'Core Set', 95, 'Tin Star', '9', 'Hearts', 'Goods', 1, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Wanted dudes cannot refuse a call-out from this dude.', NULL, 'assets/cards/core/095.png'),
(136, 'Core Set', 18, 'Tommy Harden', '3', 'Spades', 'Dude', 5, NULL, NULL, '1', NULL, 'Stud', '1', NULL, 'Law Dogs', 'Deputy', 'If your opponent in Tommy’s shootout reveals a cheatin’ hand, raise your draw hand rank by 1 for this round.#xD;\nIf your draw hand is also legal, raise your hand rank by 2 instead.', NULL, 'assets/cards/core/018.png'),
(137, 'Core Set', 49, 'Travis Moone', '5', 'Spades', 'Dude', 2, NULL, NULL, '2', NULL, 'Draw', NULL, NULL, 'Drifter', 'Grifter', 'Grifter (You may only have one Grifter in your starting posse.)\r\nReact, Boot: At the start of the game, shuffle your play hand into your deck and draw 5 cards.', NULL, 'assets/cards/core/049.png'),
(138, 'Core Set', 110, 'Tresspassin''', '2', 'Clubs', 'Action', NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: Choose a Private deed you own. Other players’ dudes there must move home booted, or gain 1 bounty each.', NULL, 'assets/cards/core/110.png'),
(139, 'Core Set', 12, 'Tyxarglenak', 'J', 'Spades', 'Dude', 4, 1, NULL, '2', NULL, 'Stud', NULL, NULL, 'The Fourth Ring', 'Abomination', 'Abomination\r\nOther players cannot choose or affect your Hucksters at this location with action cards if they could legally choose to affect Tyxarglenak instead.', NULL, 'assets/cards/core/012.png'),
(140, 'Core Set', 76, 'Undertaker', 'J', 'Diamonds', 'Deed', 4, NULL, 1, '', NULL, NULL, NULL, 2, NULL, 'Private', 'This deed’s controller gains 2 ghost rock each time a dude is aced.', NULL, 'assets/cards/core/076.png'),
(141, 'Core Set', 134, 'Unprepared', '10', 'Clubs', 'Action', NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Shootout: Boot a dude and their attached cards. That dude gets –1 bullets and cannot use abilities. Their attached cards lose all traits, abilities, and bullet bonuses.', NULL, 'assets/cards/core/134.png'),
(142, 'Core Set', 116, 'War Paint', '4', 'Clubs', 'Action', NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon: One of your dudes gets +2 bullets.', NULL, 'assets/cards/core/116.png'),
(143, 'Core Set', 85, 'Whisky Flask', '4', 'Hearts', 'Goods', 1, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Noon, Boot: Boot this dude and discard a card from your hand to draw a card.', NULL, 'assets/cards/core/085.png'),
(144, 'Core Set', 21, 'Xiong "Wendy" Cheng', '9', 'Spades', 'Dude', 6, 1, NULL, '2', NULL, 'Stud', '1', NULL, 'Law Dogs', 'Deputy', 'Shootout, Boot: Send an opposing dude home booted.', NULL, 'assets/cards/core/021.png'),
(145, 'Core Set', 60, 'Yan Li''s Tailoring', '3', 'Diamonds', 'Deed', 3, NULL, 2, '', NULL, NULL, NULL, 1, NULL, 'Private', 'Controller Noon, Boot: Raise a dude’s influence by 1.', NULL, 'assets/cards/core/060.png');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
